name: codacy-coverage-reporter

on:
  push:
    branches: [master]

jobs:
  # jest-tests:
  #   runs-on: ubuntu-latest
  #   name: jest-tests
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: npm ci
  #     - run: npm test
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          node-version: '12'
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
